[package]
name = "hearth"
version = "0.0.3"

[dependencies]
rand = "0.5"
futures = "0.1"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
actix = "0.7"
actix-web = "0.7"
ssh2 = "0.3"

[profile.release]
lto = true
opt-level = 3
