[package]
name = "hearth"
version = "0.0.1"

[dependencies]
rand = "0.5"
futures = "0.1"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
actix = "0.5"
actix-web = "0.6"
ssh2 = "0.3"

